# Generated by Django 4.2.7 on 2026-08-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('batch_type', models.CharField(max_length=50)),
                ('submitted_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('partner_webhook', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='batches_bat_status_7a0087_idx'), models.Index(fields=['batch_type'], name='batches_bat_batch_t_dfb6ab_idx'), models.Index(fields=['created_at'], name='batches_bat_created_0ab802_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('sample_id',), name='unique_sample_id'),
        ),
    ]
